schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "bioxelnodes"
version = "0.2.2"
name = "Bioxel Nodes"
tagline = "For scientific volumetric data visualization in Blender"
maintainer = "Ma Nan <icrdr2010@outlook.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "clipboard" (to read and/or write the system clipboard)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
permissions = ["files"]

# Optional link to documentation, support, source files, etc
website = "https://omoolab.github.io/BioxelNodes/latest"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Geometry Nodes", "Render", "Material"]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = ["SPDX:MIT"]
# Optional: required by some licenses.
copyright = ["2024 OmooLab"]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
platforms = ["windows-amd64", "macos-x86_64"]
# Other supported platforms: "windows-arm64", "macos-x86_64"

# TODO: externalpackage to wheels
# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/extensions/python_wheels.html
wheels = [
  "./wheels/SimpleITK-2.3.1-cp311-cp311-win_amd64.whl",
  "./wheels/SimpleITK-2.3.1-cp311-cp311-macosx_11_0_arm64.whl",
]

# Optional: build setting.
# https://docs.blender.org/manual/en/dev/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "/.git/"
#   "__pycache__/"
# ]
